from _typeshed import Incomplete

class MwClientError(RuntimeError): ...
class MediaWikiVersionError(MwClientError): ...
class APIDisabledError(MwClientError): ...
class MaximumRetriesExceeded(MwClientError): ...

class APIError(MwClientError):
    code: str
    info: str
    def __init__(self, code, info, kwargs) -> None: ...

class InsufficientPermission(MwClientError): ...
class UserBlocked(APIError): ...
class EditError(APIError): ...

class ProtectedPageError(APIError):
    page: Incomplete
    code: str
    info: str
    def __init__(self, page, code=None, info=None) -> None: ...

class FileExists(EditError):
    file_name: Incomplete
    def __init__(self, file_name) -> None: ...

class LoginError(MwClientError):
    site: Incomplete
    code: Incomplete
    info: Incomplete
    def __init__(self, site, code, info) -> None: ...

class OAuthAuthorizationError(LoginError): ...

class AssertUserFailedError(APIError):
    def __init__(self) -> None: ...

class EmailError(MwClientError): ...
class NoSpecifiedEmail(EmailError): ...
class NoWriteApi(MwClientError): ...

class InvalidResponse(MwClientError):
    response_text: Incomplete
    def __init__(self, response_text=None) -> None: ...

class InvalidPageTitle(MwClientError): ...
