from collections.abc import Generator

from _typeshed import Incomplete

def parse_timestamp(t): ...
def read_in_chunks(stream, chunk_size) -> Generator[Incomplete]: ...
def handle_limit(limit, max_items, api_chunk_size): ...
