name: Auto Update Toolforge

on:
    push:
        branches:
            - main
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Test workspace
              run: |
                  echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE" # /home/runner/work/mdwiki.org_scripts/mdwiki.org_scripts # ls -al

            - name: Copy files to server
              uses: appleboy/scp-action@v1.0.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: 22
                  source: "./"
                  target: "~/mdw_repo_tmp"
                  rm: true

            - name: Deploy on Toolforge
              uses: appleboy/ssh-action@v1.2.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  request_pty: true
                  script_stop: true
                  key: ${{ secrets.KEY }}
                  script: |
                      become mdw bash -lc "
                        rm -rf ~/tmp_repo &&
                        cp -r /mnt/nfs/labstore-secondary-tools-home/${{ secrets.USERNAME }}/mdw_repo_tmp ~/tmp_repo &&
                        cp -r ~/tmp_repo/toolforge_tool/shs/* ~/shs &&
                        sed -i 's/\r$//' ~/shs/*.sh &&
                        chmod +x ~/shs/*.sh &&
                        toolforge-jobs run update-repo --image python3.13 --command ~/shs/update.sh --wait &&
                        rm -rf ~/tmp_repo &&
                        toolforge-jobs run pipup --image python3.13 --command ~/shs/pip.sh --wait &&
                        toolforge-webservice python3.13 status &&
                        toolforge-webservice python3.13 stop &&
                        toolforge-webservice python3.13 start &&
                        echo ''
                      "
                      rm -rf mdw_repo_tmp
